/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera */

#ifndef _Included_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
#define _Included_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
 * Method:    showDebugLog
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_showDebugLog
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
 * Method:    acquireCamera
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_acquireCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
 * Method:    releaseCamera
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_releaseCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
 * Method:    takePicture
 * Signature: (JLcom/github/ajsnarr98/hauntedgameboard/hardware/camera/RealLibCamera/RawPicture;)I
 */
JNIEXPORT jint JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_takePicture
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
 * Method:    cxxConstruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_cxxConstruct
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera
 * Method:    cxxDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_cxxDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
