/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion */

#ifndef _Included_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
#define _Included_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
 * Method:    showDebugLog
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_00024Companion_showDebugLog
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
 * Method:    acquireCamera
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_00024Companion_acquireCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
 * Method:    releaseCamera
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_00024Companion_releaseCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
 * Method:    takePicture
 * Signature: (JLcom/github/ajsnarr98/hauntedgameboard/hardware/camera/RealLibCamera/RawPicture;)I
 */
JNIEXPORT jint JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_00024Companion_takePicture
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
 * Method:    cxxConstruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_00024Companion_cxxConstruct
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_Companion
 * Method:    cxxDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_ajsnarr98_hauntedgameboard_hardware_camera_RealLibCamera_00024Companion_cxxDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
